parameters:
#    hackspace_uni_chat.example.class: HackspaceUni\ChatBundle\Example

services:
#    hackspace_uni_chat.example:
#        class: %hackspace_uni_chat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
