parameters:
#    hackspace_uni_user.example.class: HackspaceUni\UserBundle\Example

services:
#    hackspace_uni_user.example:
#        class: %hackspace_uni_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
